# Generated by Django 3.0.5 on 2020-05-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='owner',
            new_name='ueser',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='owner',
            new_name='user',
        ),
    ]
