# Generated by Django 3.0.5 on 2020-05-08 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_wishlist', '0003_auto_20200508_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
