# Generated by Django 3.0.5 on 2020-05-11 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_wishlist', '0004_wishlist_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
