# Generated by Django 3.0.5 on 2020-05-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_wishlist', '0006_auto_20200512_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='title',
            new_name='wish_title',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='following',
        ),
    ]
