# Generated by Django 3.0.5 on 2020-05-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_wishlist', '0007_auto_20200512_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wish_title',
            new_name='title',
        ),
    ]
