# Generated by Django 3.0.5 on 2020-05-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_wishlist', '0010_wishlist_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='following',
            new_name='followed_by',
        ),
    ]
